version: '3'

services:
  server:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../:/var/www/food-api
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      PHP_IDE_CONFIG: "serverName=php_server"
    ports:
      - '9000:9000'
    volumes:
      - ../:/var/www/food-api:rw
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:rw
    depends_on:
      - database

  database:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./database/data:/var/lib/postgresql/data:rw